---
title: Project title
author: by Team name
output: github_document
---

## Summary

Although pacing varies, a 5-minute speech is roughly 750 words. 

You can also load your data here and present any analysis results / plots, but I strongly urge you to keep that to a minimum (maybe only the most important graphic, if you have one you can choose). 
And make sure to hide your code with  `echo = FALSE` unless the point you are trying to make is about the code itself.
Your results with proper output and graphics go in your presentation, this space is for a brief summary of your project.


In this project, we took a look into COA's fossil fuel consumption and requirements for on campus buildings. David Gibson provided the dataset that he and others worked to make. We wanted to find out how well COA is approaching 2030 fossil fuel free energy commitments. The most important variables that we used the most were "Building, Gallons, Delivery Date, Fuel Type", and our data covered about 9-10 years worth of time. We cleaned up the Fuel Type's to be easier to read/understand, combined parts of Turrets all into one to represent turrets, and set out focus on just 4 buildings in the dataset. The buildings were Turrets, Blair Tyson, Davis Center, and Seafox. 


Delving straight into the data we did some general visualizations for the whole campus over the 10 years to see how many fossil fuels have been used, and built a cumulative sum of gallons that would be able to graph the total gallons of fuel reported delivered in one Week, Month, or Year. 
We then began narrowing our filter to just our 4 main buildings, and showed that of our 4 buildings, they used primarily Heating Oil for years, as well as Liquid Propane in some buildings, and starting in 2022 Fuel Oil as well. Fuel oil and Heating oil are essentially the same and are being treated as so by David Gibson for the college. Coastal biodiesal has also been seen in the dataset as a pilot test, but hasn't been used in any real number to analyze in this project. Next was a  graph showing gallons used by year across our 4 buildings combined, showing a significant decrease starting right at 2020. We then faceted the buildings so we could see how they all changed during this time. Blair Tyson has a couple bumps, but seems to be the major contributing factor for a major decrease in fuel usage since 2018. All three other buildings seem to follow suit and decrease by much slighter margins starting 2019 to 2021, depending on which building. 
LAILA PLEASE HELP ME EXPLAIN THE EMMISSIONS GRAPHS:
The emissions appear to decrease very similarly to the previous graphs, but possibly to an even greater degree as fuel/heating oil is required slightly less, which create much more emissions than liquid propane.

Analyzing and comparing the fuel use between years by week is another good way at showing the reality of uncertainty of Winter in Maine. No two years in the same building looks exactly the same, due to differences in weather and storms, when they hit and for how long. How early winters begin/end, and when they are able to get refuels and ensure all buildings are able to be heated and used. These variables and the economics of fossil fuels make any analysis on the cost of fuel difficult to do and one we ended up avoiding in this project. 

For conclusions, arts and science and Gates take are a massive portion of total fuel use, but some of the other largest and four buildings that we chose are improving in fuel consumption. Blair Tyson has improved massively, but all insulation and heat pump installations are having a visible impact on our fuel usage.
We were not the ones who recorded this data, nor have we done a comprehensive analysis of all on campus buildings/housing, just samples of large factors. Data for the past 6 months have not yet been added but once they are it will provide the oppurunity for a full year analysis with much more accurate findings as to the results of 2030 fossil fuel independence progress. 
Any new renovations/installations and data collection will aid in future analysis, and including other buildings on campus for future work would be vital in the true progress for 2030 commitments. As heat pumps are installed and data is collected in off-campus buildings with heat pumps already, the primary focus will eventually turn to energy consumption and insulation projects as well. 





```{r load-data, echo = FALSE}
# load data here, if you like
```

## Presentation

Our presentation can be found [here](https://docs.google.com/presentation/d/1t2GxDbUH6NDmP4Pe5QId8575PwLDZYPMa0FtLBfIIRo/edit).

## Data 

Include a citation for your data here. 
See http://libraryguides.vu.edu.au/c.php?g=386501&p=4347840 for guidance on proper citation for datasets. 
If you got your data off the web, make sure to note the retrieval date.

## References

List any references here. You should, at a minimum, list your data source.
David Gibson
Laurie Baker


